# Generated by Django 2.2.1 on 2019-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Precio'),
        ),
    ]
