# Generated by Django 2.2.1 on 2019-06-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190601_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='True', null=True, upload_to='products', verbose_name='Imagen'),
        ),
    ]
